language: python
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - "python setup.py install"
  - "pip install pytest pytest-cov coveralls"

script: coverage run --source rafter -m py.test tests/
after_success:
  coveralls

matrix:
  allow_failures: # uvloop breaks on these versions
    - python: "3.5-dev"
    - python: "nightly"